spring.application.name=todo

# Development
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
debug=true

# Spring Security
#spring.security.user.name=admin
#spring.security.user.password=admin
#spring.security.user.roles=ADMIN

spring.mvc.problemdetails.enabled=true
spring.mvc.hiddenmethod.filter.enabled=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/pos}
spring.datasource.username=${DB_USER_NAME:root}
spring.datasource.password=${DB_PASSWORD:abcd}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Flyway Configuration Options
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# JPA
# Important: turn this OFF once Flyway is in charge
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true